#! /usr/bin/env python
"""Generate Bulk PKCS12
__version__ = '0.1'
__author__ = 'Stuart Wilson'
Script to generate batch of pkcs12 files based on a request file as input:
"""

import pykeytool.pykeytool
import fileinput
import os

if __name__ == '__main__':
    #Iterate over id's listed in file
    requestfile = os.path.join("C:\Work\Temp\pykeytool", "requests.txt")
    f_input= fileinput.input(files=(requestfile))
    for id in f_input:
        #Strip off newline chars
        id = id.strip()
        #Generate Certificates
        context = 14142
        pykeytool.pykeytool.update_offline_pkcs12(id, "password")

    f_input.close()
